#!/usr/bin/env python3
#
# This file is part of the LibreOffice project.
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# Generates a C++ source holding a read-only file tree for lo_embeddedfs_register().
#
#   embed_files.py OUTPUT.cxx SYMBOL DEST=SOURCE...
#
# DEST is the path inside the tree, SOURCE the file on disk; a SOURCE that is a directory
# is embedded recursively below DEST. GCC and Clang pull the data in with .incbin, so large
# files cost no compile time; other compilers get a byte array.

import hashlib
import os
import sys


def collect(pairs):
    files = {}
    for pair in pairs:
        dest, _, source = pair.partition("=")
        if not source:
            sys.exit("bad argument (want DEST=SOURCE): " + pair)
        if os.path.isdir(source):
            for root, dirs, names in os.walk(source):
                dirs.sort()
                for name in sorted(names):
                    path = os.path.join(root, name)
                    rel = os.path.relpath(path, source).replace(os.sep, "/")
                    files[dest.rstrip("/") + "/" + rel] = path
        else:
            files[dest] = source
    return sorted(files.items())


def asm_string(path):
    return path.replace("\\", "/").replace('"', '\\"')


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    output, symbol = sys.argv[1], sys.argv[2]
    files = collect(sys.argv[3:])

    out = []
    out.append("// Generated by slim/embed_files.py. Do not edit.\n")
    out.append("#include <stddef.h>\n#include <osl/detail/embeddedfs.h>\n\n")
    out.append("#if (defined __GNUC__ || defined __clang__) && (defined __ELF__ || defined __APPLE__)\n")
    out.append("#if defined __APPLE__\n#define SLIM_SECTION \".const_data\\n\"\n#define SLIM_SYM(s) \"_\" s\n")
    out.append("#else\n#define SLIM_SECTION \".section .rodata\\n\"\n#define SLIM_SYM(s) s\n#endif\n")
    for i, (dest, source) in enumerate(files):
        name = "%s_%d" % (symbol, i)
        out.append('extern "C" const unsigned char %s[];\n' % name)
        out.append('__asm__(SLIM_SECTION ".balign 16\\n" ".globl " SLIM_SYM("%s") "\\n" SLIM_SYM("%s") ":\\n"'
                   ' ".incbin \\"%s\\"\\n" ".byte 0\\n" ".previous\\n");\n'
                   % (name, name, asm_string(os.path.abspath(source))))
    out.append("#else\n")
    for i, (dest, source) in enumerate(files):
        with open(source, "rb") as f:
            data = f.read()
        out.append('extern "C" const unsigned char %s_%d[] = {' % (symbol, i))
        for j in range(0, len(data), 32):
            out.append("\n" + ",".join(str(b) for b in data[j:j + 32]) + ",")
        out.append("0};\n")
    out.append("#endif\n\n")

    out.append('extern "C" const lo_embedded_file %s[] = {\n' % symbol)
    for i, (dest, source) in enumerate(files):
        with open(source, "rb") as f:
            digest = hashlib.sha256(f.read()).hexdigest()
        # the digest makes the generated file, and so the object, change with the data
        out.append('    { "%s", %s_%d, %d }, // %s\n' % (dest, symbol, i, os.path.getsize(source), digest))
    out.append("};\n")
    out.append('extern "C" const size_t %s_count = %d;\n' % (symbol, len(files)))

    text = "".join(out)
    try:
        with open(output) as f:
            if f.read() == text:
                os.utime(output)
                return
    except OSError:
        pass
    with open(output, "w") as f:
        f.write(text)


if __name__ == "__main__":
    main()
